import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout';

const About = () => {
  return (
    <Layout home>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Link href='/'>
        <a className=''>home</a>
      </Link>
    </Layout>
  );
};
export default About;
