import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/layout';
import MyApp from '../components/MyApp/myApp';

const Home: NextPage = () => {
  return (
    <Layout home>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className='flex flex-col items-center p-4'>
          <h1 className='text-red-500'>
            Welcome to <a href='https://nextjs.org'>Next.js!</a>
          </h1>
          <div>
            <Link href='/about'>
              <a className=''>about</a>
            </Link>
          </div>

          <p className='my-16 text-2xl'>
            Get started by editing{' '}
            <code className='bg-gray-300 rounded-2xl p-3 text-xl font-mono	'>pages/index.tsx</code>
          </p>
          {/* コンテンツ */}
          <div className=''>
            {/* 自分のアプリ一覧 */}
            <div className='m-8'>
              <h1 className='text-3xl font-bold'>My App</h1>

              <MyApp></MyApp>
            </div>
            {/* 自分の記事一覧 */}
            <div className='m-8'>
              <h1 className='text-3xl'>Article</h1>
            </div>
            {/* 自分のブログ一覧 */}
            <div>
              <h1>Blog</h1>
            </div>
            {/* なんか適当に画像 */}
            <div>
              <h1>Image</h1>
            </div>
          </div>

          <div className='flex items-center justify-center flex-wrap max-w-screen-md'>
            <a
              href='https://nextjs.org/docs'
              className='m-4 p-6 text-left no-underline border-solid border border-gray-200 rounded-lg max-w-xs transition-colors duration-150 ease-linear hover:border-blue-600 hover:text-blue-600 '
            >
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a
              href='https://nextjs.org/learn'
              className='m-4 p-6 text-left no-underline border-solid border border-gray-200 rounded-lg max-w-xs transition-colors duration-150 ease-linear hover:border-blue-600 hover:text-blue-600 '
            >
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href='https://github.com/vercel/next.js/tree/canary/examples'
              className='m-4 p-6 text-left no-underline border-solid border border-gray-200 rounded-lg max-w-xs transition-colors duration-150 ease-linear hover:border-blue-600 hover:text-blue-600 '
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              className='m-4 p-6 text-left no-underline border-solid border border-gray-200 rounded-lg max-w-xs transition-colors duration-150 ease-linear hover:border-blue-600 hover:text-blue-600 '
            >
              <h2>Deploy &rarr;</h2>
              <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
            </a>
          </div>
        </main>

        <footer className='flex flex-grow flex-shrink p-8 border-solid border-t justify-center items-center'>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
          >
            Powered by{' '}
            <span className='h-4 ml-2'>
              <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  );
};

export default Home;
